name: katamaran_ground_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  dart_mavlink: ^0.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # window_manager: ^0.5.1
  # gamepads: ^0.1.10+2
  share_plus: ^10.0.0
  # win32_gamepad: ^1.0.4
  flutter_libserialport: ^0.4.0
  # desktop_multi_window: ^0.3.0
  # media_kit: ^1.2.6
  # media_kit_video: ^2.0.1
  # media_kit_libs_windows_video: ^1.0.11
  # desktop_multi_window: ^0.2.1
  # fvp: ^0.33.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ship.png
    - assets/arrow.png
