name: katamaran_ground_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  dart_mavlink: ^0.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  share_plus: ^10.0.0
  flutter_libserialport: ^0.4.0
  shared_preferences: ^2.5.3
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ship.png
    - assets/arrow.png
    - assets/parameters/apm.pdef.xml
