import 'package:flutter/material.dart';

import '../../../data/mavlink_data.dart';
import '../../../services/notifier_service.dart';
import '../widgets/pwm_output_tile.dart';

class PwmOutputMonitor extends StatelessWidget {
  PwmOutputMonitor({super.key});

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: const Color(0xFF1B1D22),
      child: SizedBox(
        width: 520,
        height: 570,
        child: Padding(
          padding: EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  const Text(
                    "PWM Output Monitor",
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const Spacer(),
                  IconButton(
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    icon: Icon(Icons.close, color: Colors.red),
                  ),
                ],
              ),
              const SizedBox(height: 4),
              const Text(
                "Inspect PWM Output generated by ship controller.",
                style: TextStyle(color: Colors.white54),
              ),
              const SizedBox(height: 20),
              Expanded(
                child: ValueListenableBuilder(
                  valueListenable: NotifierService.pwmTrigger,
                  builder: (context, _, _) {
                    return ListView.separated(
                      itemBuilder: (context, index) {
                        return PwmOutputTile(
                          output: index + 1,
                          value: MavlinkData.pwmOutput[index],
                        );
                      },
                      separatorBuilder: (_, _) {
                        return const SizedBox(height: 2);
                      },
                      itemCount: 16,
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
